#!/bin/zsh
# Claude Code CC Aliases
# Terminal shortcuts to launch Claude with team-specific agent personas
# Generated by AITeamForge installer — uses direct --system-prompt passing
# NOTE: stdin piping (echo | claude --system-prompt -) breaks in tmux contexts
# This file is a template — {{ORG_NAME}}, {{ORG_SLUG}}, etc. are substituted
# at install time by the AITeamForge installer. Do not edit the rendered copy.

# Installation directory (substituted during install)
AITEAMFORGE_DIR="{{AITEAMFORGE_DIR}}"

# ─────────────────────────────────────────────────────────────────────────────
# Core Infrastructure
# ─────────────────────────────────────────────────────────────────────────────

# Remove any existing cc/ccc aliases before defining functions
unalias cc 2>/dev/null
unalias ccc 2>/dev/null

# Encode working directory to match Claude Code's project directory naming
# /Users/darrenehlers/dev-team → -Users-darrenehlers-dev-team
_cc_encode_project_dir() {
    local dir="${1:-$(pwd)}"
    echo "$dir" | sed 's|[/ ]|-|g; s|^-||'
}

# Print "-w<window_index>" when running inside tmux; return non-zero otherwise.
# Scopes saved session files to a specific tmux window so two windows running
# the same persona don't clobber each other's resume state.
_cc_window_suffix() {
    [[ -z "$TMUX" ]] && return 1
    local idx
    if [[ -n "$TMUX_PANE" ]]; then
        idx=$(tmux display-message -t "$TMUX_PANE" -p '#I' 2>/dev/null)
    else
        idx=$(tmux display-message -p '#I' 2>/dev/null)
    fi
    [[ -z "$idx" ]] && return 1
    echo "-w${idx}"
}

# Derive a human-readable session name mirroring what the agent panel's
# MISSION section displays: kanban task → "ITEM-ID: item title" → first
# user message from the transcript. Truncated to 40 chars. Empty if none
# of the sources yield a usable value.
_cc_derive_session_name() {
    local transcript="$1"
    local name=""

    # Sources 1 & 2: kanban board (same lookup logic as get_kanban_info
    # in scripts/agent-panel-display.sh, trimmed to the fields we need).
    if typeset -f _kb_detect_context &>/dev/null; then
        local context team terminal window_name board_file window_id info
        context=$(_kb_detect_context 2>/dev/null)
        if [[ -n "$context" && "$context" != "ERROR:ERROR:0:unknown" ]]; then
            team="${context%%:*}"
            local rest="${context#*:}"
            terminal="${rest%%:*}"
            rest="${rest#*:}"
            window_name="${rest#*:}"
            board_file=$(_kb_get_board_file "$team" 2>/dev/null)
            window_id=$(_kb_get_window_id "$terminal" "$window_name" 2>/dev/null)

            if [[ -f "$board_file" && -n "$window_id" ]]; then
                info=$(_kb_jq_read "$board_file" '
                    (.activeWindows // []) as $wins |
                    (.backlog // []) as $bl |
                    ($wins | map(select(.id == $wid)) | first // null) as $aw |
                    if $aw == null then ""
                    else
                        ($aw.task // "") as $task |
                        (if $aw.workingOnId then
                            ($bl | map(select(.id == $aw.workingOnId)) | first // null)
                         else
                            ($bl | map(
                                if .worktreeWindowId == $wid then .
                                elif ((.subitems // []) | map(select(.worktreeWindowId == $wid)) | length) > 0 then
                                    (.subitems | map(select(.worktreeWindowId == $wid)) | first)
                                else null end
                            ) | map(select(. != null)) | first // null)
                         end) as $item |
                        "\($task)\t\($item.id // "")\t\($item.title // "")"
                    end
                ' --arg wid "$window_id" -r 2>/dev/null)

                local task item_id item_title
                IFS=$'\t' read -r task item_id item_title <<< "$info"
                if [[ -n "$task" ]]; then
                    name="$task"
                elif [[ -n "$item_id" ]]; then
                    name="${item_id}: ${item_title}"
                fi
            fi
        fi
    fi

    # Source 3: first user message from transcript (only when kanban is silent).
    if [[ -z "$name" && -f "$transcript" ]]; then
        name=$(python3 - "$transcript" <<'PY'
import json, sys
try:
    with open(sys.argv[1]) as fp:
        for line in fp:
            try: p = json.loads(line)
            except Exception: continue
            if p.get('type') != 'user' or p.get('isSidechain'):
                continue
            c = (p.get('message') or {}).get('content')
            text = None
            if isinstance(c, str):
                text = c
            elif isinstance(c, list):
                for part in c:
                    if isinstance(part, dict) and part.get('type') == 'text':
                        text = part.get('text'); break
            if text:
                print(' '.join(text.split()))
                break
except Exception:
    pass
PY
        )
    fi

    # Collapse whitespace, strip pipes (record separator), cap at 40 chars.
    name="${name//$'\n'/ }"
    name="${name//$'\r'/ }"
    name="${name//|/ }"
    if (( ${#name} > 40 )); then
        name="${name:0:37}..."
    fi
    printf '%s' "$name"
}

# Save the most recent Claude session ID for the current tmux window, the
# display name derived from the MISSION panel state, and the current project
# dir so ccc can cd back to it on resume (XACA-0177). Sidecar file format is
# "<uuid>|<name>|<project_dir>" (pipe-delimited; name and dir may be empty).
# Skipped outside tmux — no per-window scope to attach to.
#
# XACA-0541 — Optional $1: a known session UUID (pinned via --session-id at
# launch). When supplied and valid, skips the ls -t heuristic entirely — no
# project_dir lookup needed. Callers that don't supply $1 (ccc --resume /
# --continue) keep the existing ls -t fallback behaviour unchanged.
_cc_save_session() {
    [[ -z "$SESSION_CODE" ]] && return 0

    local window_suffix
    window_suffix=$(_cc_window_suffix) || return 0

    # Accept an optional known UUID from the caller (e.g. _cc_launch pinned id).
    local _cc_known_id="${1:-}"

    local session_id=""
    local latest_file=""

    if [[ "$_cc_known_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
        # Fast path: use the pinned UUID directly; no filesystem probe needed.
        session_id="$_cc_known_id"
        # latest_file stays empty — _cc_derive_session_name handles that gracefully.
    else
        # Fallback path (used by ccc --resume / --continue): probe the project dir.
        local encoded_dir
        encoded_dir=$(_cc_encode_project_dir)
        local project_dir="$HOME/.claude/projects/-${encoded_dir}"

        [[ ! -d "$project_dir" ]] && return 0

        # Find the most recently modified session .jsonl file
        latest_file=$(ls -t "$project_dir"/*.jsonl 2>/dev/null | head -1)
        [[ -z "$latest_file" ]] && return 0

        session_id=$(basename "$latest_file" .jsonl)

        # Validate UUID format
        [[ "$session_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] || return 0
    fi

    local session_name
    session_name=$(_cc_derive_session_name "$latest_file")

    mkdir -p "$HOME/.claude/terminal-sessions"
    printf '%s|%s|%s\n' "$session_id" "$session_name" "$PWD" \
        > "$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"
}

# Read the saved-session sidecar for the current tmux window and echo the
# display-name portion (empty if unset, missing, or legacy uuid-only file).
# Used by team banner scripts to render the "Saved Session:" line.
_cc_saved_session_label() {
    [[ -z "$SESSION_CODE" ]] && return 0

    local window_suffix
    window_suffix=$(_cc_window_suffix) || return 0

    local session_file="$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"
    [[ -f "$session_file" ]] || return 0

    local session_id saved_name saved_dir
    IFS='|' read -r session_id saved_name saved_dir < "$session_file"
    printf '%s' "$saved_name"
}

# Helper: launch Claude Code with a system prompt file
# Uses direct argument passing (NOT stdin piping, which breaks in tmux)
# Set CC_DEBUG=1 for preview only
_cc_launch() {
    local prompt_file="$1"

    # Read prompt text directly
    if [[ ! -f "$prompt_file" ]]; then
        echo "ERROR: Prompt file not found: $prompt_file" >&2
        return 1
    fi

    CLAUDE_SYSTEM_PROMPT="$(<"$prompt_file")"

    if [[ -z "$CLAUDE_SYSTEM_PROMPT" ]]; then
        echo "ERROR: CLAUDE_SYSTEM_PROMPT is empty after reading $prompt_file" >&2
        return 1
    fi

    # --- XACA-0541: session name -------------------------------------------
    # Start from caller-supplied env var; fall back to kanban/transcript derive.
    local _cc_name="${CC_SESSION_NAME:-}"
    if [[ -z "$_cc_name" ]]; then
        _cc_name=$(_cc_derive_session_name "")
    fi
    # Sanitize regardless of source: collapse newlines/whitespace, strip pipes,
    # cap at 40 chars (mirrors the sanitize block in _cc_derive_session_name).
    _cc_name="${_cc_name//$'\n'/ }"
    _cc_name="${_cc_name//$'\r'/ }"
    _cc_name="${_cc_name//|/ }"
    if (( ${#_cc_name} > 40 )); then
        _cc_name="${_cc_name:0:37}..."
    fi

    # --- XACA-0541: pinned session-id --------------------------------------
    # Feature-detect once; generate a lowercase UUID when supported.
    local _cc_has_session_id=""
    claude --help 2>/dev/null | grep -q -- "--session-id" && _cc_has_session_id=1
    local _cc_pinned_id=""
    if [[ -n "$_cc_has_session_id" ]]; then
        _cc_pinned_id=$(uuidgen | tr 'A-Z' 'a-z')
    fi

    if [[ "$CC_DEBUG" == "1" ]]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "CC_DEBUG=1 — Preview Only"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Prompt file: $prompt_file"
        echo "Prompt length: ${#CLAUDE_SYSTEM_PROMPT} chars"
        echo "Session name: ${_cc_name:-(none)}"
        echo "Pinned session-id: ${_cc_pinned_id:-(none — feature not supported)}"
        echo ""
        echo "First 500 chars:"
        echo "${CLAUDE_SYSTEM_PROMPT:0:500}"
        echo "..."
        return 0
    fi

    # Build optional flag array — empty values are simply omitted.
    local -a _cc_extra_args=()
    [[ -n "$_cc_name" ]] && _cc_extra_args+=(--name "$_cc_name")
    [[ -n "$_cc_pinned_id" ]] && _cc_extra_args+=(--session-id "$_cc_pinned_id")

    claude --permission-mode bypassPermissions "${_cc_extra_args[@]}" --append-system-prompt "$CLAUDE_SYSTEM_PROMPT" \
        "If an AMB heartbeat system reminder is present, call mcp__amb__heartbeat first, then introduce yourself briefly."

    # Pass the pinned UUID so _cc_save_session can skip the ls -t heuristic.
    _cc_save_session "$_cc_pinned_id"

    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
}

# Context-aware cc command — detects terminal SESSION_TYPE/SESSION_NAME and
# uses the appropriate persona. Falls back to plain claude if not configured.
cc() {
    if [[ -n "$SESSION_TYPE" && -n "$SESSION_NAME" ]]; then
        local dir="${SESSION_DIR:-$SESSION_TYPE}"
        local prompt_file="$AITEAMFORGE_DIR/${dir}/scripts/prompts/${SESSION_TYPE}-${SESSION_NAME}-prompt.txt"
        if [[ -f "$prompt_file" ]]; then
            _cc_launch "$prompt_file"
            return
        else
            # XACA-0785: this branch used to silently drop straight through to
            # the persona-less fallback below — no error, no persona, and
            # nothing in colors/tmux window name/banners to reveal it. That
            # silent no-op was the core XACA-0785 bug. Warn loudly instead.
            echo "🚨 WARNING: Agent prompt file not found: $prompt_file" >&2
            echo "🚨 Falling back to plain claude — NO PERSONA (generic assistant, no character/team context)." >&2
        fi
    fi
    claude --permission-mode bypassPermissions "$@"
}

# Resume the most recent Claude session for THIS terminal
# Uses stored session ID instead of --continue (which picks most recent globally)
ccc() {
    local window_suffix
    window_suffix=$(_cc_window_suffix) || window_suffix=""
    local session_file="$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"

    if [[ -n "$SESSION_CODE" && -n "$window_suffix" && -f "$session_file" ]]; then
        # Sidecar is "<uuid>|<name>|<project_dir>" — legacy 2-field and
        # 1-field (uuid only) files parse with empty trailing vars and still
        # work with --resume.
        local session_id saved_name saved_dir
        IFS='|' read -r session_id saved_name saved_dir < "$session_file"
        if [[ -n "$session_id" ]]; then
            # XACA-0177: restore project dir so claude --resume sees the
            # same cwd that was active when the session was saved.
            if [[ -n "$saved_dir" && "$saved_dir" != "$PWD" ]]; then
                if [[ -d "$saved_dir" ]]; then
                    cd "$saved_dir" || echo "ccc: warning — cd '$saved_dir' failed, resuming from $PWD" >&2
                else
                    echo "ccc: warning — saved project dir '$saved_dir' is gone, resuming from $PWD" >&2
                fi
            fi
            claude --permission-mode bypassPermissions --resume "$session_id"
            _cc_save_session
            if command -v kb-clear &> /dev/null; then
                kb-clear
            fi
            return
        fi
    fi

    claude --permission-mode bypassPermissions --continue
    _cc_save_session
    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Pre-emptively clear any conflicting aliases
# ─────────────────────────────────────────────────────────────────────────────
unalias cc-ios-bridge cc-ios-engineering cc-ios-sickbay cc-ios-holodeck cc-ios-observation cc-ios-stellar 2>/dev/null
unalias cc-firebase-ops cc-firebase-engineering cc-firebase-holodeck cc-firebase-stellar cc-firebase-sickbay cc-firebase-observation cc-firebase-promenade 2>/dev/null
unalias cc-android-bridge cc-android-science cc-android-sickbay cc-android-engineering cc-android-communications cc-android-navigation cc-android-helm 2>/dev/null
unalias cc-freelance-command cc-freelance-engineering cc-freelance-science cc-freelance-sickbay cc-freelance-tactical cc-freelance-comms cc-freelance-helm 2>/dev/null
unalias cc-{{ORG_SLUG}}-command cc-{{ORG_SLUG}}-engineering cc-{{ORG_SLUG}}-science cc-{{ORG_SLUG}}-sickbay cc-{{ORG_SLUG}}-tactical cc-{{ORG_SLUG}}-comms cc-{{ORG_SLUG}}-helm 2>/dev/null
unalias cc-dns-command cc-dns-bugbay cc-dns-testing cc-dns-build cc-dns-refactor cc-dns-apidesign cc-dns-docs 2>/dev/null
unalias cc-academy-chancellor cc-academy-engineering cc-academy-medical cc-academy-training 2>/dev/null
unalias cc-command-admiral cc-command-operations cc-command-strategic cc-command-communications cc-command-intelligence 2>/dev/null
unalias cc-finance-nagus cc-finance-bar cc-finance-vault cc-finance-fca cc-finance-workshop 2>/dev/null

# ─────────────────────────────────────────────────────────────────────────────
# iOS Team (TNG)
# ─────────────────────────────────────────────────────────────────────────────
cc-ios-bridge() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-bridge-prompt.txt"; }
cc-ios-engineering() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-engineering-prompt.txt"; }
cc-ios-sickbay() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-sickbay-prompt.txt"; }
cc-ios-holodeck() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-holodeck-prompt.txt"; }
cc-ios-observation() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-observation-prompt.txt"; }
cc-ios-stellar() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-stellar-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Firebase Team (DS9)
# ─────────────────────────────────────────────────────────────────────────────
cc-firebase-ops() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-ops-prompt.txt"; }
cc-firebase-engineering() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-engineering-prompt.txt"; }
cc-firebase-holodeck() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-holodeck-prompt.txt"; }
cc-firebase-stellar() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-stellar-prompt.txt"; }
cc-firebase-sickbay() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-sickbay-prompt.txt"; }
cc-firebase-observation() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-observation-prompt.txt"; }
cc-firebase-promenade() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-promenade-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Android Team (TOS)
# ─────────────────────────────────────────────────────────────────────────────
cc-android-bridge() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-bridge-prompt.txt"; }
cc-android-science() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-science-prompt.txt"; }
cc-android-sickbay() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-sickbay-prompt.txt"; }
cc-android-engineering() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-engineering-prompt.txt"; }
cc-android-communications() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-communications-prompt.txt"; }
cc-android-navigation() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-navigation-prompt.txt"; }
cc-android-helm() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-helm-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Freelance Team (ENT)
# ─────────────────────────────────────────────────────────────────────────────
cc-freelance-command() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-command-prompt.txt"; }
cc-freelance-engineering() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-engineering-prompt.txt"; }
cc-freelance-science() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-science-prompt.txt"; }
cc-freelance-sickbay() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-sickbay-prompt.txt"; }
cc-freelance-tactical() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-tactical-prompt.txt"; }
cc-freelance-comms() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-comms-prompt.txt"; }
cc-freelance-helm() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-helm-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# {{ORG_NAME}} Team (VOY) — org plugin provides prompts at {{ORG_SLUG}}/scripts/prompts/
# ─────────────────────────────────────────────────────────────────────────────
cc-{{ORG_SLUG}}-command() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-command-prompt.txt"
}
cc-{{ORG_SLUG}}-engineering() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-engineering-prompt.txt"
}
cc-{{ORG_SLUG}}-science() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-SCIENCE"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-science-prompt.txt"
}
cc-{{ORG_SLUG}}-sickbay() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-SICKBAY"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-sickbay-prompt.txt"
}
cc-{{ORG_SLUG}}-tactical() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-TACTICAL"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-tactical-prompt.txt"
}
cc-{{ORG_SLUG}}-comms() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-COMMS"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-comms-prompt.txt"
}
cc-{{ORG_SLUG}}-helm() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-HELM"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-helm-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# DNS Framework Team (LD)
# ─────────────────────────────────────────────────────────────────────────────
cc-dns-command() {
    export CLAUDE_DNS_THEME="LD-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-command-prompt.txt"
}
cc-dns-bugbay() {
    export CLAUDE_DNS_THEME="LD-BUGBAY"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-bugbay-prompt.txt"
}
cc-dns-testing() {
    export CLAUDE_DNS_THEME="LD-TESTING"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-testing-prompt.txt"
}
cc-dns-build() {
    export CLAUDE_DNS_THEME="LD-BUILD"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-build-prompt.txt"
}
cc-dns-refactor() {
    export CLAUDE_DNS_THEME="LD-REFACTOR"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-refactor-prompt.txt"
}
cc-dns-apidesign() {
    export CLAUDE_DNS_THEME="LD-APIDESIGN"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-apidesign-prompt.txt"
}
cc-dns-docs() {
    export CLAUDE_DNS_THEME="LD-DOCS"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-docs-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Academy Team (32nd Century)
# ─────────────────────────────────────────────────────────────────────────────
cc-academy-chancellor() {
    export CLAUDE_ACADEMY_THEME="CHANCELLOR"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-chancellor-prompt.txt"
}
cc-academy-engineering() {
    export CLAUDE_ACADEMY_THEME="ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-engineering-prompt.txt"
}
cc-academy-medical() {
    export CLAUDE_ACADEMY_THEME="MEDICAL"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-medical-prompt.txt"
}
cc-academy-training() {
    export CLAUDE_ACADEMY_THEME="TRAINING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-training-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Command Team (DSC)
# ─────────────────────────────────────────────────────────────────────────────
cc-command-admiral() {
    export CLAUDE_COMMAND_THEME="ADMIRAL"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-admiral-prompt.txt"
}
cc-command-operations() {
    export CLAUDE_COMMAND_THEME="OPERATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-operations-prompt.txt"
}
cc-command-strategic() {
    export CLAUDE_COMMAND_THEME="STRATEGIC"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-strategic-prompt.txt"
}
cc-command-communications() {
    export CLAUDE_COMMAND_THEME="COMMUNICATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-communications-prompt.txt"
}
cc-command-intelligence() {
    export CLAUDE_COMMAND_THEME="INTELLIGENCE"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-intelligence-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Finance Team (Ferengi Alliance)
# ─────────────────────────────────────────────────────────────────────────────
cc-finance-nagus() {
    export CLAUDE_FINANCE_THEME="NAGUS"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-nagus-prompt.txt"
}
cc-finance-bar() {
    export CLAUDE_FINANCE_THEME="BAR"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-bar-prompt.txt"
}
cc-finance-vault() {
    export CLAUDE_FINANCE_THEME="VAULT"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-vault-prompt.txt"
}
cc-finance-fca() {
    export CLAUDE_FINANCE_THEME="FCA"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-fca-prompt.txt"
}
cc-finance-workshop() {
    export CLAUDE_FINANCE_THEME="WORKSHOP"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-workshop-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# GitHub Bot Tools
# ─────────────────────────────────────────────────────────────────────────────
alias gh-bot-review='bash ~/.config/gh-review-bot/gh-bot-review.sh'
alias gh-bot-test='bash ~/.config/gh-tester-bot/gh-bot-test.sh'

echo "✓ CC aliases loaded (use 'cc-help' for list)"

cc-help() {
    echo ""
    echo "Claude Code CC Aliases"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "iOS (TNG):        cc-ios-bridge, cc-ios-engineering, cc-ios-sickbay"
    echo "                  cc-ios-holodeck, cc-ios-observation, cc-ios-stellar"
    echo ""
    echo "Firebase (DS9):   cc-firebase-ops, cc-firebase-engineering, cc-firebase-holodeck"
    echo "                  cc-firebase-stellar, cc-firebase-sickbay, cc-firebase-observation"
    echo "                  cc-firebase-promenade"
    echo ""
    echo "Android (TOS):    cc-android-bridge, cc-android-science, cc-android-sickbay"
    echo "                  cc-android-engineering, cc-android-communications"
    echo "                  cc-android-navigation, cc-android-helm"
    echo ""
    echo "Freelance (ENT):  cc-freelance-command, cc-freelance-engineering"
    echo "                  cc-freelance-science, cc-freelance-sickbay"
    echo "                  cc-freelance-tactical, cc-freelance-comms, cc-freelance-helm"
    echo ""
    echo "{{ORG_NAME}} (VOY): cc-{{ORG_SLUG}}-command, cc-{{ORG_SLUG}}-engineering"
    echo "                   cc-{{ORG_SLUG}}-science, cc-{{ORG_SLUG}}-sickbay"
    echo "                   cc-{{ORG_SLUG}}-tactical, cc-{{ORG_SLUG}}-comms, cc-{{ORG_SLUG}}-helm"
    echo ""
    echo "DNS (LD):         cc-dns-command, cc-dns-bugbay, cc-dns-testing, cc-dns-build"
    echo "                  cc-dns-refactor, cc-dns-apidesign, cc-dns-docs"
    echo ""
    echo "Academy (32nd):   cc-academy-chancellor, cc-academy-engineering"
    echo "                  cc-academy-medical, cc-academy-training"
    echo ""
    echo "Command (DSC):    cc-command-admiral, cc-command-operations, cc-command-strategic"
    echo "                  cc-command-communications, cc-command-intelligence"
    echo ""
    echo "Finance (Ferengi): cc-finance-nagus, cc-finance-bar, cc-finance-vault"
    echo "                   cc-finance-fca, cc-finance-workshop"
    echo ""
    echo "Core:             cc (context-aware launch), ccc (resume session)"
    echo ""
    echo "Set CC_DEBUG=1 to preview prompt without launching Claude"
    echo ""
}
