#!/bin/zsh
# Claude Code CC Aliases
# Terminal shortcuts to launch Claude with team-specific agent personas
# Generated by AITeamForge installer — uses direct --system-prompt passing
# NOTE: stdin piping (echo | claude --system-prompt -) breaks in tmux contexts

# Installation directory (substituted during install)
AITEAMFORGE_DIR="{{AITEAMFORGE_DIR}}"

# ─────────────────────────────────────────────────────────────────────────────
# Core Infrastructure
# ─────────────────────────────────────────────────────────────────────────────

# Remove any existing cc/ccc aliases before defining functions
unalias cc 2>/dev/null
unalias ccc 2>/dev/null

# Encode working directory to match Claude Code's project directory naming
# /Users/darrenehlers/dev-team → -Users-darrenehlers-dev-team
_cc_encode_project_dir() {
    local dir="${1:-$(pwd)}"
    echo "$dir" | sed 's|/|-|g; s|^-||'
}

# Save the most recent Claude session ID for the current terminal
# Enables per-terminal session resume via ccc
_cc_save_session() {
    [[ -z "$SESSION_CODE" ]] && return 0

    local encoded_dir
    encoded_dir=$(_cc_encode_project_dir)
    local project_dir="$HOME/.claude/projects/-${encoded_dir}"

    [[ ! -d "$project_dir" ]] && return 0

    # Find the most recently modified session .jsonl file
    local latest_file
    latest_file=$(ls -t "$project_dir"/*.jsonl 2>/dev/null | head -1)
    [[ -z "$latest_file" ]] && return 0

    # Staleness guard: only save if file was modified in the last 60 seconds
    local now file_mtime age
    now=$(date +%s)
    file_mtime=$(stat -f %m "$latest_file" 2>/dev/null)
    if [[ -n "$file_mtime" ]]; then
        age=$(( now - file_mtime ))
        if (( age > 60 )); then
            return 0
        fi
    fi

    local session_id
    session_id=$(basename "$latest_file" .jsonl)

    # Validate UUID format
    if [[ "$session_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
        mkdir -p "$HOME/.claude/terminal-sessions"
        echo "$session_id" > "$HOME/.claude/terminal-sessions/${SESSION_CODE}"
    fi
}

# Helper: launch Claude Code with a system prompt file
# Uses direct argument passing (NOT stdin piping, which breaks in tmux)
# Set CC_DEBUG=1 for preview only
_cc_launch() {
    local prompt_file="$1"

    # Read .txt file directly — sourcing .sh files breaks in tmux (${0:a:h} resolves wrong)
    local txt_file="${prompt_file%.sh}.txt"

    if [[ ! -f "$txt_file" ]]; then
        echo "ERROR: Prompt file not found: $txt_file" >&2
        return 1
    fi

    CLAUDE_SYSTEM_PROMPT="$(<"$txt_file")"

    if [[ -z "$CLAUDE_SYSTEM_PROMPT" ]]; then
        echo "ERROR: CLAUDE_SYSTEM_PROMPT is empty after reading $txt_file" >&2
        return 1
    fi

    if [[ "$CC_DEBUG" == "1" ]]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "CC_DEBUG=1 — Preview Only"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Prompt file: $prompt_file"
        echo "Prompt length: ${#CLAUDE_SYSTEM_PROMPT} chars"
        echo ""
        echo "First 500 chars:"
        echo "${CLAUDE_SYSTEM_PROMPT:0:500}"
        echo "..."
        return 0
    fi

    claude --permission-mode bypassPermissions --append-system-prompt "$CLAUDE_SYSTEM_PROMPT" \
        "If an AMB heartbeat system reminder is present, call mcp__amb__heartbeat first, then introduce yourself briefly."

    _cc_save_session

    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
}

# Context-aware cc command — detects terminal SESSION_TYPE/SESSION_NAME and
# uses the appropriate persona. Falls back to plain claude if not configured.
cc() {
    if [[ -n "$SESSION_TYPE" && -n "$SESSION_NAME" ]]; then
        local dir="${SESSION_DIR:-$SESSION_TYPE}"
        local prompt_file="$AITEAMFORGE_DIR/${dir}/scripts/prompts/${SESSION_TYPE}-${SESSION_NAME}-prompt.sh"
        if [[ -f "${prompt_file%.sh}.txt" ]]; then
            _cc_launch "$prompt_file"
            return
        fi
    fi
    claude --permission-mode bypassPermissions "$@"
}

# Resume the most recent Claude session for THIS terminal
# Uses stored session ID instead of --continue (which picks most recent globally)
ccc() {
    local session_file="$HOME/.claude/terminal-sessions/${SESSION_CODE}"

    if [[ -n "$SESSION_CODE" && -f "$session_file" ]]; then
        local session_id
        session_id=$(<"$session_file")
        if [[ -n "$session_id" ]]; then
            claude --permission-mode bypassPermissions --resume "$session_id"
            _cc_save_session
            if command -v kb-clear &> /dev/null; then
                kb-clear
            fi
            return
        fi
    fi

    claude --permission-mode bypassPermissions --continue
    _cc_save_session
    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# Pre-emptively clear any conflicting aliases
# ─────────────────────────────────────────────────────────────────────────────
unalias cc-ios-bridge cc-ios-engineering cc-ios-sickbay cc-ios-holodeck cc-ios-observation cc-ios-stellar 2>/dev/null
unalias cc-firebase-ops cc-firebase-engineering cc-firebase-holodeck cc-firebase-stellar cc-firebase-sickbay cc-firebase-observation cc-firebase-promenade 2>/dev/null
unalias cc-android-bridge cc-android-science cc-android-sickbay cc-android-engineering cc-android-communications cc-android-navigation cc-android-helm 2>/dev/null
unalias cc-freelance-command cc-freelance-engineering cc-freelance-science cc-freelance-sickbay cc-freelance-tactical cc-freelance-comms cc-freelance-helm 2>/dev/null
unalias cc-mainevent-command cc-mainevent-engineering cc-mainevent-science cc-mainevent-sickbay cc-mainevent-tactical cc-mainevent-comms cc-mainevent-helm 2>/dev/null
unalias cc-dns-command cc-dns-bugbay cc-dns-testing cc-dns-build cc-dns-refactor cc-dns-apidesign cc-dns-docs 2>/dev/null
unalias cc-academy-chancellor cc-academy-engineering cc-academy-medical cc-academy-training 2>/dev/null
unalias cc-command-admiral cc-command-operations cc-command-strategic cc-command-communications cc-command-intelligence 2>/dev/null
unalias cc-finance-nagus cc-finance-bar cc-finance-vault cc-finance-fca cc-finance-workshop 2>/dev/null

# ─────────────────────────────────────────────────────────────────────────────
# iOS Team (TNG)
# ─────────────────────────────────────────────────────────────────────────────
cc-ios-bridge() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-bridge-prompt.sh"; }
cc-ios-engineering() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-engineering-prompt.sh"; }
cc-ios-sickbay() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-sickbay-prompt.sh"; }
cc-ios-holodeck() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-holodeck-prompt.sh"; }
cc-ios-observation() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-observation-prompt.sh"; }
cc-ios-stellar() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-stellar-prompt.sh"; }

# ─────────────────────────────────────────────────────────────────────────────
# Firebase Team (DS9)
# ─────────────────────────────────────────────────────────────────────────────
cc-firebase-ops() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-ops-prompt.sh"; }
cc-firebase-engineering() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-engineering-prompt.sh"; }
cc-firebase-holodeck() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-holodeck-prompt.sh"; }
cc-firebase-stellar() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-stellar-prompt.sh"; }
cc-firebase-sickbay() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-sickbay-prompt.sh"; }
cc-firebase-observation() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-observation-prompt.sh"; }
cc-firebase-promenade() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-promenade-prompt.sh"; }

# ─────────────────────────────────────────────────────────────────────────────
# Android Team (TOS)
# ─────────────────────────────────────────────────────────────────────────────
cc-android-bridge() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-bridge-prompt.sh"; }
cc-android-science() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-science-prompt.sh"; }
cc-android-sickbay() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-sickbay-prompt.sh"; }
cc-android-engineering() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-engineering-prompt.sh"; }
cc-android-communications() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-communications-prompt.sh"; }
cc-android-navigation() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-navigation-prompt.sh"; }
cc-android-helm() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-helm-prompt.sh"; }

# ─────────────────────────────────────────────────────────────────────────────
# Freelance Team (ENT)
# ─────────────────────────────────────────────────────────────────────────────
cc-freelance-command() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-command-prompt.sh"; }
cc-freelance-engineering() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-engineering-prompt.sh"; }
cc-freelance-science() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-science-prompt.sh"; }
cc-freelance-sickbay() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-sickbay-prompt.sh"; }
cc-freelance-tactical() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-tactical-prompt.sh"; }
cc-freelance-comms() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-comms-prompt.sh"; }
cc-freelance-helm() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-helm-prompt.sh"; }

# ─────────────────────────────────────────────────────────────────────────────
# MainEvent Team (VOY)
# ─────────────────────────────────────────────────────────────────────────────
cc-mainevent-command() {
    export CLAUDE_MAINEVENT_THEME="VOY-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-command-prompt.sh"
}
cc-mainevent-engineering() {
    export CLAUDE_MAINEVENT_THEME="VOY-ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-engineering-prompt.sh"
}
cc-mainevent-science() {
    export CLAUDE_MAINEVENT_THEME="VOY-SCIENCE"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-science-prompt.sh"
}
cc-mainevent-sickbay() {
    export CLAUDE_MAINEVENT_THEME="VOY-SICKBAY"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-sickbay-prompt.sh"
}
cc-mainevent-tactical() {
    export CLAUDE_MAINEVENT_THEME="VOY-TACTICAL"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-tactical-prompt.sh"
}
cc-mainevent-comms() {
    export CLAUDE_MAINEVENT_THEME="VOY-COMMS"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-comms-prompt.sh"
}
cc-mainevent-helm() {
    export CLAUDE_MAINEVENT_THEME="VOY-HELM"
    _cc_launch "$AITEAMFORGE_DIR/mainevent/scripts/prompts/mainevent-helm-prompt.sh"
}

# ─────────────────────────────────────────────────────────────────────────────
# DNS Framework Team (LD)
# ─────────────────────────────────────────────────────────────────────────────
cc-dns-command() {
    export CLAUDE_DNS_THEME="LD-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-command-prompt.sh"
}
cc-dns-bugbay() {
    export CLAUDE_DNS_THEME="LD-BUGBAY"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-bugbay-prompt.sh"
}
cc-dns-testing() {
    export CLAUDE_DNS_THEME="LD-TESTING"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-testing-prompt.sh"
}
cc-dns-build() {
    export CLAUDE_DNS_THEME="LD-BUILD"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-build-prompt.sh"
}
cc-dns-refactor() {
    export CLAUDE_DNS_THEME="LD-REFACTOR"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-refactor-prompt.sh"
}
cc-dns-apidesign() {
    export CLAUDE_DNS_THEME="LD-APIDESIGN"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-apidesign-prompt.sh"
}
cc-dns-docs() {
    export CLAUDE_DNS_THEME="LD-DOCS"
    _cc_launch "$AITEAMFORGE_DIR/dns-framework/scripts/prompts/dns-docs-prompt.sh"
}

# ─────────────────────────────────────────────────────────────────────────────
# Academy Team (32nd Century)
# ─────────────────────────────────────────────────────────────────────────────
cc-academy-chancellor() {
    export CLAUDE_ACADEMY_THEME="CHANCELLOR"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-chancellor-prompt.sh"
}
cc-academy-engineering() {
    export CLAUDE_ACADEMY_THEME="ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-engineering-prompt.sh"
}
cc-academy-medical() {
    export CLAUDE_ACADEMY_THEME="MEDICAL"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-medical-prompt.sh"
}
cc-academy-training() {
    export CLAUDE_ACADEMY_THEME="TRAINING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-training-prompt.sh"
}

# ─────────────────────────────────────────────────────────────────────────────
# Command Team (DSC)
# ─────────────────────────────────────────────────────────────────────────────
cc-command-admiral() {
    export CLAUDE_COMMAND_THEME="ADMIRAL"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-admiral-prompt.sh"
}
cc-command-operations() {
    export CLAUDE_COMMAND_THEME="OPERATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-operations-prompt.sh"
}
cc-command-strategic() {
    export CLAUDE_COMMAND_THEME="STRATEGIC"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-strategic-prompt.sh"
}
cc-command-communications() {
    export CLAUDE_COMMAND_THEME="COMMUNICATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-communications-prompt.sh"
}
cc-command-intelligence() {
    export CLAUDE_COMMAND_THEME="INTELLIGENCE"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-intelligence-prompt.sh"
}

# ─────────────────────────────────────────────────────────────────────────────
# Finance Team (Ferengi Alliance)
# ─────────────────────────────────────────────────────────────────────────────
cc-finance-nagus() {
    export CLAUDE_FINANCE_THEME="NAGUS"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-nagus-prompt.sh"
}
cc-finance-bar() {
    export CLAUDE_FINANCE_THEME="BAR"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-bar-prompt.sh"
}
cc-finance-vault() {
    export CLAUDE_FINANCE_THEME="VAULT"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-vault-prompt.sh"
}
cc-finance-fca() {
    export CLAUDE_FINANCE_THEME="FCA"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-fca-prompt.sh"
}
cc-finance-workshop() {
    export CLAUDE_FINANCE_THEME="WORKSHOP"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-workshop-prompt.sh"
}

# ─────────────────────────────────────────────────────────────────────────────
# GitHub Bot Tools
# ─────────────────────────────────────────────────────────────────────────────
alias gh-bot-review='bash ~/.config/gh-review-bot/gh-bot-review.sh'
alias gh-bot-test='bash ~/.config/gh-tester-bot/gh-bot-test.sh'

echo "✓ CC aliases loaded (use 'cc-help' for list)"

cc-help() {
    echo ""
    echo "Claude Code CC Aliases"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "iOS (TNG):        cc-ios-bridge, cc-ios-engineering, cc-ios-sickbay"
    echo "                  cc-ios-holodeck, cc-ios-observation, cc-ios-stellar"
    echo ""
    echo "Firebase (DS9):   cc-firebase-ops, cc-firebase-engineering, cc-firebase-holodeck"
    echo "                  cc-firebase-stellar, cc-firebase-sickbay, cc-firebase-observation"
    echo "                  cc-firebase-promenade"
    echo ""
    echo "Android (TOS):    cc-android-bridge, cc-android-science, cc-android-sickbay"
    echo "                  cc-android-engineering, cc-android-communications"
    echo "                  cc-android-navigation, cc-android-helm"
    echo ""
    echo "Freelance (ENT):  cc-freelance-command, cc-freelance-engineering"
    echo "                  cc-freelance-science, cc-freelance-sickbay"
    echo "                  cc-freelance-tactical, cc-freelance-comms, cc-freelance-helm"
    echo ""
    echo "MainEvent (VOY):  cc-mainevent-command, cc-mainevent-engineering"
    echo "                  cc-mainevent-science, cc-mainevent-sickbay"
    echo "                  cc-mainevent-tactical, cc-mainevent-comms, cc-mainevent-helm"
    echo ""
    echo "DNS (LD):         cc-dns-command, cc-dns-bugbay, cc-dns-testing, cc-dns-build"
    echo "                  cc-dns-refactor, cc-dns-apidesign, cc-dns-docs"
    echo ""
    echo "Academy (32nd):   cc-academy-chancellor, cc-academy-engineering"
    echo "                  cc-academy-medical, cc-academy-training"
    echo ""
    echo "Command (DSC):    cc-command-admiral, cc-command-operations, cc-command-strategic"
    echo "                  cc-command-communications, cc-command-intelligence"
    echo ""
    echo "Finance (Ferengi): cc-finance-nagus, cc-finance-bar, cc-finance-vault"
    echo "                   cc-finance-fca, cc-finance-workshop"
    echo ""
    echo "Core:             cc (context-aware launch), ccc (resume session)"
    echo ""
    echo "Set CC_DEBUG=1 to preview prompt without launching Claude"
    echo ""
}
