#!/bin/zsh
# Claude Code CC Aliases
# Terminal shortcuts to launch Claude with team-specific agent personas
# Generated by AITeamForge installer — uses direct --system-prompt passing
# NOTE: stdin piping (echo | claude --system-prompt -) breaks in tmux contexts
# This file is a template — {{ORG_NAME}}, {{ORG_SLUG}}, etc. are substituted
# at install time by the AITeamForge installer. Do not edit the rendered copy.

# Installation directory (substituted during install)
AITEAMFORGE_DIR="{{AITEAMFORGE_DIR}}"

# XACA-1312: the credential-routing core (design doc §1.1, §6) — the SAME
# file dev claude_code_cc_aliases.sh sources, shipped here so a consumer's
# cc/cc-*/ccc launches actually apply the team's declared ai.credential
# instead of always billing the machine login. Tap-Only-Edit: intentional
# (this template is not in sync-tap.sh's mirror map — grep confirms only
# comment hits — so this source line and the _cc_launch/cc/ccc wiring below
# are native to this file, not derived from the canonical launcher).
#
# Fail-closed on a missing/broken core: a partial upgrade or a non-zsh shell
# must refuse cc/cc-*/ccc rather than silently launch unrouted (design §6,
# "if the core fails to load"). _cc_routing_core_missing is what every
# wired launch site below checks before doing anything else.
#
# XACA-1312 fix round 1 (bot review, PR #957): the message below has always
# promised that AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1 launches on the machine
# login even when the core itself is missing -- design §6's own escape
# hatch. Until this fix the function returned 1 unconditionally, so the
# override did nothing here (verified: core absent + override set + `ccc`
# still refused). Every call site below now branches on THIS return value
# instead of hardcoding `return 1` -- see each site's own comment.
_cc_routing_core_missing() {
    if [[ "${AITEAMFORGE_ALLOW_DEFAULT_OAUTH:-0}" == "1" ]]; then
        print -u2 "⚠ AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1 — routing core missing at $AITEAMFORGE_DIR/scripts/cc-account-routing.sh — this session bills the MACHINE LOGIN, not any declared team credential"
        return 0
    fi
    print -u2 "✗ routing core missing at $AITEAMFORGE_DIR/scripts/cc-account-routing.sh — run 'aiteamforge upgrade' (or AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1 to launch on the machine login)"
    return 1
}
if [[ -f "$AITEAMFORGE_DIR/scripts/cc-account-routing.sh" ]]; then
    source "$AITEAMFORGE_DIR/scripts/cc-account-routing.sh" || true
fi
# XACA-1312 fix round 1 (bot review, PR #957): every wired launch site below
# calls _cc_run_claude_with_auth UNCONDITIONALLY after its missing-core
# check -- fine when the core loaded (it defines the real function), but
# under AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1 with the core ABSENT,
# _cc_routing_core_missing now returns 0 and lets the site fall through to
# a function that was never defined ("command not found", rc 127) --
# discovered by this round's own new missing-core-override test. This shim
# only ever receives an EMPTY token when it runs (resolution never ran
# either in that branch), so it is equivalent to a bare `claude "$@"` --
# the same shape as the real function's own -z "$_cc_token" fast path.
if ! command -v _cc_run_claude_with_auth >/dev/null 2>&1; then
    _cc_run_claude_with_auth() {
        shift 2
        claude "$@"
    }
fi
# Same reasoning as the shim above, for _cc_record_session_account (also
# core-defined, also called unconditionally by every launch site below).
# Silent no-op, matching the real function's own documented fail-soft
# contract ("Silent no-op when the recorder is absent ... never aborts a
# launch") -- there is no recorder to call when the core never loaded.
if ! command -v _cc_record_session_account >/dev/null 2>&1; then
    _cc_record_session_account() { :; }
fi
# Same reasoning again for _cc_resume_account_guard (ccc's cross-account
# resume check, also core-defined). With no core there is no map-lookup
# infra to check against, so this shim always ALLOWS the resume (return 0)
# -- refusing here would defeat the override's whole purpose (a partial or
# broken install must still be able to launch/resume under explicit
# consent).
if ! command -v _cc_resume_account_guard >/dev/null 2>&1; then
    _cc_resume_account_guard() { return 0; }
fi

# ─────────────────────────────────────────────────────────────────────────────
# Core Infrastructure
# ─────────────────────────────────────────────────────────────────────────────

# Remove any existing cc/ccc aliases before defining functions
unalias cc 2>/dev/null
unalias ccc 2>/dev/null

# Encode working directory to match Claude Code's project directory naming
# /Users/darrenehlers/dev-team → -Users-darrenehlers-dev-team
_cc_encode_project_dir() {
    local dir="${1:-$(pwd)}"
    echo "$dir" | sed 's|[/ ]|-|g; s|^-||'
}

# Print "-w<window_index>" when running inside tmux; return non-zero otherwise.
# Scopes saved session files to a specific tmux window so two windows running
# the same persona don't clobber each other's resume state.
_cc_window_suffix() {
    [[ -z "$TMUX" ]] && return 1
    local idx
    if [[ -n "$TMUX_PANE" ]]; then
        idx=$(tmux display-message -t "$TMUX_PANE" -p '#I' 2>/dev/null)
    else
        idx=$(tmux display-message -p '#I' 2>/dev/null)
    fi
    [[ -z "$idx" ]] && return 1
    echo "-w${idx}"
}

# Derive a human-readable session name mirroring what the agent panel's
# MISSION section displays: kanban task → "ITEM-ID: item title" → first
# user message from the transcript. Truncated to 40 chars. Empty if none
# of the sources yield a usable value.
_cc_derive_session_name() {
    local transcript="$1"
    local name=""

    # Sources 1 & 2: kanban board (same lookup logic as get_kanban_info
    # in scripts/agent-panel-display.sh, trimmed to the fields we need).
    if typeset -f _kb_detect_context &>/dev/null; then
        local context team terminal window_name board_file window_id info
        context=$(_kb_detect_context 2>/dev/null)
        if [[ -n "$context" && "$context" != "ERROR:ERROR:0:unknown" ]]; then
            team="${context%%:*}"
            local rest="${context#*:}"
            terminal="${rest%%:*}"
            rest="${rest#*:}"
            window_name="${rest#*:}"
            board_file=$(_kb_get_board_file "$team" 2>/dev/null)
            window_id=$(_kb_get_window_id "$terminal" "$window_name" 2>/dev/null)

            if [[ -f "$board_file" && -n "$window_id" ]]; then
                info=$(_kb_jq_read "$board_file" '
                    (.activeWindows // []) as $wins |
                    (.backlog // []) as $bl |
                    ($wins | map(select(.id == $wid)) | first // null) as $aw |
                    if $aw == null then ""
                    else
                        ($aw.task // "") as $task |
                        (if $aw.workingOnId then
                            ($bl | map(select(.id == $aw.workingOnId)) | first // null)
                         else
                            ($bl | map(
                                if .worktreeWindowId == $wid then .
                                elif ((.subitems // []) | map(select(.worktreeWindowId == $wid)) | length) > 0 then
                                    (.subitems | map(select(.worktreeWindowId == $wid)) | first)
                                else null end
                            ) | map(select(. != null)) | first // null)
                         end) as $item |
                        "\($task)\t\($item.id // "")\t\($item.title // "")"
                    end
                ' --arg wid "$window_id" -r 2>/dev/null)

                local task item_id item_title
                IFS=$'\t' read -r task item_id item_title <<< "$info"
                if [[ -n "$task" ]]; then
                    name="$task"
                elif [[ -n "$item_id" ]]; then
                    name="${item_id}: ${item_title}"
                fi
            fi
        fi
    fi

    # Source 3: first user message from transcript (only when kanban is silent).
    if [[ -z "$name" && -f "$transcript" ]]; then
        name=$(python3 - "$transcript" <<'PY'
import json, sys
try:
    with open(sys.argv[1]) as fp:
        for line in fp:
            try: p = json.loads(line)
            except Exception: continue
            if p.get('type') != 'user' or p.get('isSidechain'):
                continue
            c = (p.get('message') or {}).get('content')
            text = None
            if isinstance(c, str):
                text = c
            elif isinstance(c, list):
                for part in c:
                    if isinstance(part, dict) and part.get('type') == 'text':
                        text = part.get('text'); break
            if text:
                print(' '.join(text.split()))
                break
except Exception:
    pass
PY
        )
    fi

    # Collapse whitespace, strip pipes (record separator), cap at 40 chars.
    name="${name//$'\n'/ }"
    name="${name//$'\r'/ }"
    name="${name//|/ }"
    if (( ${#name} > 40 )); then
        name="${name:0:37}..."
    fi
    printf '%s' "$name"
}

# Save the most recent Claude session ID for the current tmux window, the
# display name derived from the MISSION panel state, and the current project
# dir so ccc can cd back to it on resume (XACA-0177). Sidecar file format is
# "<uuid>|<name>|<project_dir>" (pipe-delimited; name and dir may be empty).
# Skipped outside tmux — no per-window scope to attach to.
#
# XACA-0541 — Optional $1: a known session UUID (pinned via --session-id at
# launch). When supplied and valid, skips the ls -t heuristic entirely — no
# project_dir lookup needed. Callers that don't supply $1 (ccc --resume /
# --continue) keep the existing ls -t fallback behaviour unchanged.
_cc_save_session() {
    [[ -z "$SESSION_CODE" ]] && return 0

    local window_suffix
    window_suffix=$(_cc_window_suffix) || return 0

    # Accept an optional known UUID from the caller (e.g. _cc_launch pinned id).
    local _cc_known_id="${1:-}"

    local session_id=""
    local latest_file=""

    if [[ "$_cc_known_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
        # Fast path: use the pinned UUID directly; no filesystem probe needed.
        session_id="$_cc_known_id"
        # latest_file stays empty — _cc_derive_session_name handles that gracefully.
    else
        # Fallback path (used by ccc --resume / --continue): probe the project dir.
        local encoded_dir
        encoded_dir=$(_cc_encode_project_dir)
        local project_dir="$HOME/.claude/projects/-${encoded_dir}"

        [[ ! -d "$project_dir" ]] && return 0

        # Find the most recently modified session .jsonl file
        latest_file=$(ls -t "$project_dir"/*.jsonl 2>/dev/null | head -1)
        [[ -z "$latest_file" ]] && return 0

        session_id=$(basename "$latest_file" .jsonl)

        # Validate UUID format
        [[ "$session_id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] || return 0
    fi

    local session_name
    session_name=$(_cc_derive_session_name "$latest_file")

    mkdir -p "$HOME/.claude/terminal-sessions"
    printf '%s|%s|%s\n' "$session_id" "$session_name" "$PWD" \
        > "$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"
}

# Read the saved-session sidecar for the current tmux window and echo the
# display-name portion (empty if unset, missing, or legacy uuid-only file).
# Used by team banner scripts to render the "Saved Session:" line.
_cc_saved_session_label() {
    [[ -z "$SESSION_CODE" ]] && return 0

    local window_suffix
    window_suffix=$(_cc_window_suffix) || return 0

    local session_file="$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"
    [[ -f "$session_file" ]] || return 0

    local session_id saved_name saved_dir
    IFS='|' read -r session_id saved_name saved_dir < "$session_file"
    printf '%s' "$saved_name"
}

# XACA-0223 (ported from canonical claude_code_cc_aliases.sh — see FAULT C,
# XACA-1144): deterministic clear of the iTerm2 tab "C " prefix.
# The stop-hook daemon (kanban-stop.py) is a heuristic that can miss slow
# Claude shutdowns. Here we know `claude` has exited because its process
# returned — fire clear_claude_active synchronously. Refcount semantics
# still prevent over-clearing when multiple Claude sessions share a tab.
# Fallback chain matches the other three call sites (kanban-session-start.py,
# kanban-stop.py, update_claude_agent.sh): $DEV_TEAM_ROOT override first,
# since ~/dev-team never exists on a consumer, then ~/aiteamforge.
# Silent no-op when the helper is absent — this file is sourced into every
# interactive shell, so a missing helper must never break the terminal.
_cc_clear_claude_active() {
    local _cc_badge_helper=""
    if [[ -n "${DEV_TEAM_ROOT:-}" && -f "${DEV_TEAM_ROOT}/iterm2_badge_helper.sh" ]]; then
        _cc_badge_helper="$DEV_TEAM_ROOT/iterm2_badge_helper.sh"
    elif [[ -f "$HOME/dev-team/iterm2_badge_helper.sh" ]]; then
        _cc_badge_helper="$HOME/dev-team/iterm2_badge_helper.sh"
    elif [[ -f "$HOME/aiteamforge/iterm2_badge_helper.sh" ]]; then
        _cc_badge_helper="$HOME/aiteamforge/iterm2_badge_helper.sh"
    fi
    if [[ -n "$_cc_badge_helper" ]]; then
        source "$_cc_badge_helper" && clear_claude_active
    fi
}

# Helper: launch Claude Code with a system prompt file
# Uses direct argument passing (NOT stdin piping, which breaks in tmux)
# Set CC_DEBUG=1 for preview only
_cc_launch() {
    local prompt_file="$1"

    # XACA-0977 BLOCKING A parity (dev claude_code_cc_aliases.sh): a GLOBAL,
    # out-of-band signal telling cc() whether claude was ever actually
    # invoked, separate from this function's return code. Pre-clear FIRST —
    # before any early-abort path below — so a stale "1" from a PRIOR
    # successful call in this shell can't leak through.
    _CC_LAUNCH_INVOKED=0

    # Read prompt text directly
    if [[ ! -f "$prompt_file" ]]; then
        echo "ERROR: Prompt file not found: $prompt_file" >&2
        return 1
    fi

    # XACA-1312 (design doc §4, site #1): resolve and apply the team's
    # declared ai.credential right after the prompt-file checks, via the
    # SAME shared core dev claude_code_cc_aliases.sh uses. A missing core
    # (partial upgrade, or a non-zsh shell) refuses rather than launching
    # unrouted (design §6) -- UNLESS AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1, in
    # which case _cc_routing_core_missing itself returns 0 and we fall
    # through with the token/id locals left empty (default OAuth, per
    # fix round 1 / bot review on PR #957).
    local _CC_RESOLVED_TOKEN="" _CC_RESOLVED_AUTH_TYPE=""
    local _CC_BILLED_ID="" _CC_BILLED_NICKNAME=""
    if command -v _cc_route_prepare >/dev/null 2>&1; then
        _cc_route_prepare
        if [[ $? -eq 1 ]]; then
            echo "ERROR: Cannot resolve Anthropic token for this team — aborting launch" >&2
            return 1
        fi
    elif ! _cc_routing_core_missing; then
        return 1
    fi

    CLAUDE_SYSTEM_PROMPT="$(<"$prompt_file")"

    if [[ -z "$CLAUDE_SYSTEM_PROMPT" ]]; then
        echo "ERROR: CLAUDE_SYSTEM_PROMPT is empty after reading $prompt_file" >&2
        return 1
    fi

    # --- XACA-0541: session name -------------------------------------------
    # Start from caller-supplied env var; fall back to kanban/transcript derive.
    local _cc_name="${CC_SESSION_NAME:-}"
    if [[ -z "$_cc_name" ]]; then
        _cc_name=$(_cc_derive_session_name "")
    fi
    # Sanitize regardless of source: collapse newlines/whitespace, strip pipes,
    # cap at 40 chars (mirrors the sanitize block in _cc_derive_session_name).
    _cc_name="${_cc_name//$'\n'/ }"
    _cc_name="${_cc_name//$'\r'/ }"
    _cc_name="${_cc_name//|/ }"
    if (( ${#_cc_name} > 40 )); then
        _cc_name="${_cc_name:0:37}..."
    fi

    # --- XACA-0541: pinned session-id --------------------------------------
    # Feature-detect once; generate a lowercase UUID when supported.
    local _cc_has_session_id=""
    claude --help 2>/dev/null | grep -q -- "--session-id" && _cc_has_session_id=1
    local _cc_pinned_id=""
    if [[ -n "$_cc_has_session_id" ]]; then
        _cc_pinned_id=$(uuidgen | tr 'A-Z' 'a-z')
    fi

    if [[ "$CC_DEBUG" == "1" ]]; then
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "CC_DEBUG=1 — Preview Only"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "Prompt file: $prompt_file"
        echo "Prompt length: ${#CLAUDE_SYSTEM_PROMPT} chars"
        echo "Session name: ${_cc_name:-(none)}"
        echo "Pinned session-id: ${_cc_pinned_id:-(none — feature not supported)}"
        echo ""
        echo "First 500 chars:"
        echo "${CLAUDE_SYSTEM_PROMPT:0:500}"
        echo "..."
        return 0
    fi

    # XACA-1312 (design doc §0 D3 correction, §4 CLAUDE_BILLED_ACCOUNT_ID
    # contract): record via the shared helper with the GATED billed
    # identity _cc_route_prepare just resolved — NOT the old headless
    # helper's own recording rule, which reads CLAUDE_BILLED_ACCOUNT_ID from
    # the CALLING shell's environment. That is empty even on a successful
    # route: the token only ever reaches claude's CHILD env via
    # _cc_run_claude_with_auth's subshell, so the headless helper's rule 1
    # would have recorded every routed tap launch as default OAuth —
    # exactly the mis-record this ticket exists to fix. Record at LAUNCH
    # time (crash-safe, XACA-0668 parity) using the local pin above.
    _cc_record_session_account "$_cc_pinned_id" "$_CC_BILLED_ID" "$_CC_BILLED_NICKNAME"

    # Build optional flag array — empty values are simply omitted.
    local -a _cc_extra_args=()
    [[ -n "$_cc_name" ]] && _cc_extra_args+=(--name "$_cc_name")
    [[ -n "$_cc_pinned_id" ]] && _cc_extra_args+=(--session-id "$_cc_pinned_id")

    # XACA-1312: from here on claude is genuinely being invoked (dev parity)
    # -- flip the signal BEFORE the call, and inject the resolved credential
    # via the shared scoped-env helper instead of a bare `claude` call.
    _CC_LAUNCH_INVOKED=1
    _cc_run_claude_with_auth "$_CC_RESOLVED_TOKEN" "$_CC_RESOLVED_AUTH_TYPE" \
        --permission-mode bypassPermissions "${_cc_extra_args[@]}" --append-system-prompt "$CLAUDE_SYSTEM_PROMPT" \
        "If an AMB heartbeat system reminder is present, call mcp__amb__heartbeat first, then introduce yourself briefly."
    local _cc_launch_claude_rc=$?

    # Pass the pinned UUID so _cc_save_session can skip the ls -t heuristic.
    _cc_save_session "$_cc_pinned_id"

    # XACA-1312: post-exit record too (dev _cc_launch parity) — a session
    # may be resumable even after a non-zero exit, and billing already
    # occurred either way.
    _cc_record_session_account "$_cc_pinned_id" "$_CC_BILLED_ID" "$_CC_BILLED_NICKNAME"

    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
    _cc_clear_claude_active
    return $_cc_launch_claude_rc
}

# Context-aware cc command — detects terminal SESSION_TYPE/SESSION_NAME and
# uses the appropriate persona. Falls back to plain claude if not configured.
cc() {
    if [[ -n "$SESSION_TYPE" && -n "$SESSION_NAME" ]]; then
        local dir="${SESSION_DIR:-$SESSION_TYPE}"
        local prompt_file="$AITEAMFORGE_DIR/${dir}/scripts/prompts/${SESSION_TYPE}-${SESSION_NAME}-prompt.txt"
        if [[ -f "$prompt_file" ]]; then
            _cc_launch "$prompt_file"
            return
        else
            # XACA-0785: this branch used to silently drop straight through to
            # the persona-less fallback below — no error, no persona, and
            # nothing in colors/tmux window name/banners to reveal it. That
            # silent no-op was the core XACA-0785 bug. Warn loudly instead.
            echo "🚨 WARNING: Agent prompt file not found: $prompt_file" >&2
            echo "🚨 Falling back to plain claude — NO PERSONA (generic assistant, no character/team context)." >&2
        fi
    fi
    # XACA-1312 (design §4 site #2): plain-claude fallback -- the headless
    # gate path (`printf prompt | cc` from kb-run-* with no persona context)
    # AND the "prompt file not found" fallthrough above. Route it too,
    # whenever a team context exists, via the SAME shared core.
    local _cc_fb_team="${SESSION_TYPE:-${LCARS_TEAM:-${KB_TEAM:-}}}"
    if [[ -n "$_cc_fb_team" ]]; then
        # XACA-1312 fix round 1: same missing-core override handling as
        # site #1 above -- _cc_routing_core_missing returns 0 under
        # AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1 and we fall through unrouted.
        local _CC_RESOLVED_TOKEN="" _CC_RESOLVED_AUTH_TYPE=""
        local _CC_BILLED_ID="" _CC_BILLED_NICKNAME=""
        if command -v _cc_route_prepare >/dev/null 2>&1; then
            _cc_route_prepare
            if [[ $? -eq 1 ]]; then
                # XACA-1312 §3.3: REFUSED. claude must NOT run at all -- a
                # refusal is not a persona failure, and falling back to
                # plain unrouted claude here would reconstruct the exact
                # silent-downgrade defect this ticket exists to close.
                echo "ERROR: Cannot resolve Anthropic token for team '${_cc_fb_team}' — aborting launch" >&2
                return 1
            fi
        elif ! _cc_routing_core_missing; then
            return 1
        fi
        # Pin a session id the same way _cc_launch does (XACA-0541), only
        # when cc got NO arguments -- with arguments this may be
        # `cc --resume <id>`, `cc -c` or a subcommand, where an added
        # --session-id would conflict or break the command.
        local -a _cc_fb_extra=()
        local _cc_fb_sid=""
        if (( $# == 0 )); then
            local _cc_fb_has_sid=""
            claude --help 2>/dev/null | grep -q -- "--session-id" && _cc_fb_has_sid=1
            if [[ -n "$_cc_fb_has_sid" ]]; then
                _cc_fb_sid=$(uuidgen | tr 'A-Z' 'a-z')
                _cc_fb_extra=(--session-id "$_cc_fb_sid")
            fi
        fi
        _cc_run_claude_with_auth "$_CC_RESOLVED_TOKEN" "$_CC_RESOLVED_AUTH_TYPE" \
            --permission-mode bypassPermissions "${_cc_fb_extra[@]}" "$@"
        local _cc_fb_rc=$?
        # XACA-1312 D3 correction: record via the gated identity, never the
        # headless helper's own rule (see _cc_launch's matching comment).
        _cc_record_session_account "$_cc_fb_sid" "$_CC_BILLED_ID" "$_CC_BILLED_NICKNAME"
        return $_cc_fb_rc
    fi

    # XACA-1300-014: no team context -- nothing declared to route. Keep the
    # headless helper exactly as before; it correctly attributes a NESTED
    # headless launch (one shelled out from inside an already-routed parent
    # session) via CLAUDE_BILLED_ACCOUNT_ID inherited from that parent's
    # export. Only when cc got NO arguments: `cc --resume <id>`, `cc -c` and
    # subcommands would break or conflict with an added --session-id, so
    # they stay unrecorded. </dev/null keeps the helper's `claude --help`
    # probe off the piped gate prompt.
    local -a _cc_fb_args=()
    if (( $# == 0 )) && [[ -x "$AITEAMFORGE_DIR/scripts/session-account-map-headless.sh" ]]; then
        local _cc_fb_sid2
        _cc_fb_sid2=$("$AITEAMFORGE_DIR/scripts/session-account-map-headless.sh" </dev/null)
        [[ -n "$_cc_fb_sid2" ]] && _cc_fb_args=(--session-id "$_cc_fb_sid2")
    fi
    claude --permission-mode bypassPermissions "${_cc_fb_args[@]}" "$@"
}

# Resume the most recent Claude session for THIS terminal
# Uses stored session ID instead of --continue (which picks most recent globally)
ccc() {
    # XACA-1312 (design §5): argument parsing + routing + cross-account
    # guard parity with dev ccc(). A typo like `ccc --forse` must be a usage
    # error, not silent consent-absent.
    local _ccc_force=0
    while (( $# )); do
        case "$1" in
            --force) _ccc_force=1; shift ;;
            *)
                print -u2 "ccc: unknown argument '$1'"
                print -u2 "usage: ccc [--force]"
                return 2
                ;;
        esac
    done

    # Resolve credentials BEFORE reading the sidecar (ordering is
    # load-bearing — see dev ccc()'s own comment on this: the recorder must
    # never run against a pre-resolution empty billed id).
    #
    # XACA-1312 fix round 1: missing core is no longer an unconditional
    # refusal here either -- _cc_routing_core_missing returns 0 under
    # AITEAMFORGE_ALLOW_DEFAULT_OAUTH=1, treated the same as a successful
    # (unrouted, default-OAuth) _cc_route_prepare rc=0 below.
    local _CC_RESOLVED_TOKEN="" _CC_RESOLVED_AUTH_TYPE=""
    local _CC_BILLED_ID="" _CC_BILLED_NICKNAME=""
    local _ccc_cred_rc
    if command -v _cc_route_prepare >/dev/null 2>&1; then
        _cc_route_prepare
        _ccc_cred_rc=$?
    else
        if ! _cc_routing_core_missing; then
            return 1
        fi
        _ccc_cred_rc=0
    fi
    local resolved_account_id="$_CC_BILLED_ID"
    local resolved_account_nickname="$_CC_BILLED_NICKNAME"

    # --- D3 parity: rc=1 is fail-closed, UNCONDITIONALLY — --force does NOT
    # override. Consenting to bill account X is meaningless when no token
    # for X could be obtained.
    if [[ $_ccc_cred_rc -eq 1 ]]; then
        echo "ERROR: Cannot resolve Anthropic token — aborting resume (no session was resumed, nothing was billed)" >&2
        return 1
    fi

    local window_suffix
    window_suffix=$(_cc_window_suffix) || window_suffix=""
    local session_file="$HOME/.claude/terminal-sessions/${SESSION_CODE}${window_suffix}"

    if [[ -n "$SESSION_CODE" && -n "$window_suffix" && -f "$session_file" ]]; then
        # Sidecar is "<uuid>|<name>|<project_dir>" — legacy 2-field and
        # 1-field (uuid only) files parse with empty trailing vars and still
        # work with --resume.
        local session_id saved_name saved_dir
        IFS='|' read -r session_id saved_name saved_dir < "$session_file"
        if [[ -n "$session_id" ]]; then
            # XACA-0977 D1/D2 parity: cross-account resume guard, via the
            # shared helper (design §1.1, §5) — same implementation dev ccc
            # uses. On a mismatch with no --force it has already printed the
            # full warning; this function's only job is to return.
            if ! _cc_resume_account_guard "$session_id" "$resolved_account_id" "$_ccc_force"; then
                return 1
            fi

            # XACA-0177: restore project dir so claude --resume sees the
            # same cwd that was active when the session was saved.
            if [[ -n "$saved_dir" && "$saved_dir" != "$PWD" ]]; then
                if [[ -d "$saved_dir" ]]; then
                    cd "$saved_dir" || echo "ccc: warning — cd '$saved_dir' failed, resuming from $PWD" >&2
                else
                    echo "ccc: warning — saved project dir '$saved_dir' is gone, resuming from $PWD" >&2
                fi
            fi

            _cc_save_session "$session_id"
            _cc_record_session_account "$session_id" "$resolved_account_id" "$resolved_account_nickname"

            _cc_run_claude_with_auth "$_CC_RESOLVED_TOKEN" "$_CC_RESOLVED_AUTH_TYPE" \
                --permission-mode bypassPermissions --resume "$session_id"
            local _ccc_claude_rc=$?
            _cc_save_session
            _cc_record_session_account "$session_id" "$resolved_account_id" "$resolved_account_nickname"
            if command -v kb-clear &> /dev/null; then
                kb-clear
            fi
            _cc_clear_claude_active
            return $_ccc_claude_rc
        fi
    fi

    print -u2 $'\e[2m'"ccc: no saved session for this window — using --continue; billed to ${resolved_account_nickname:-default OAuth}"$'\e[0m'
    _cc_run_claude_with_auth "$_CC_RESOLVED_TOKEN" "$_CC_RESOLVED_AUTH_TYPE" \
        --permission-mode bypassPermissions --continue
    local _ccc_claude_rc=$?
    _cc_save_session
    if command -v kb-clear &> /dev/null; then
        kb-clear
    fi
    _cc_clear_claude_active
    return $_ccc_claude_rc
}

# ─────────────────────────────────────────────────────────────────────────────
# Pre-emptively clear any conflicting aliases
# ─────────────────────────────────────────────────────────────────────────────
unalias cc-ios-bridge cc-ios-engineering cc-ios-sickbay cc-ios-holodeck cc-ios-observation cc-ios-stellar 2>/dev/null
unalias cc-firebase-ops cc-firebase-engineering cc-firebase-holodeck cc-firebase-stellar cc-firebase-sickbay cc-firebase-observation cc-firebase-promenade 2>/dev/null
unalias cc-android-bridge cc-android-science cc-android-sickbay cc-android-engineering cc-android-communications cc-android-navigation cc-android-helm 2>/dev/null
unalias cc-freelance-command cc-freelance-engineering cc-freelance-science cc-freelance-sickbay cc-freelance-tactical cc-freelance-comms cc-freelance-helm 2>/dev/null
unalias cc-{{ORG_SLUG}}-command cc-{{ORG_SLUG}}-engineering cc-{{ORG_SLUG}}-science cc-{{ORG_SLUG}}-sickbay cc-{{ORG_SLUG}}-tactical cc-{{ORG_SLUG}}-comms cc-{{ORG_SLUG}}-helm 2>/dev/null
unalias cc-dns-command cc-dns-bugbay cc-dns-testing cc-dns-build cc-dns-refactor cc-dns-apidesign cc-dns-docs 2>/dev/null
unalias cc-academy-chancellor cc-academy-engineering cc-academy-medical cc-academy-training 2>/dev/null
unalias cc-command-admiral cc-command-operations cc-command-strategic cc-command-communications cc-command-intelligence 2>/dev/null
unalias cc-finance-nagus cc-finance-bar cc-finance-vault cc-finance-fca cc-finance-workshop 2>/dev/null

# ─────────────────────────────────────────────────────────────────────────────
# iOS Team (TNG)
# ─────────────────────────────────────────────────────────────────────────────
cc-ios-bridge() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-bridge-prompt.txt"; }
cc-ios-engineering() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-engineering-prompt.txt"; }
cc-ios-sickbay() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-sickbay-prompt.txt"; }
cc-ios-holodeck() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-holodeck-prompt.txt"; }
cc-ios-observation() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-observation-prompt.txt"; }
cc-ios-stellar() { _cc_launch "$AITEAMFORGE_DIR/ios/scripts/prompts/ios-stellar-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Firebase Team (DS9)
# ─────────────────────────────────────────────────────────────────────────────
cc-firebase-ops() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-ops-prompt.txt"; }
cc-firebase-engineering() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-engineering-prompt.txt"; }
cc-firebase-holodeck() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-holodeck-prompt.txt"; }
cc-firebase-stellar() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-stellar-prompt.txt"; }
cc-firebase-sickbay() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-sickbay-prompt.txt"; }
cc-firebase-observation() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-observation-prompt.txt"; }
cc-firebase-promenade() { _cc_launch "$AITEAMFORGE_DIR/firebase/scripts/prompts/firebase-promenade-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Android Team (TOS)
# ─────────────────────────────────────────────────────────────────────────────
cc-android-bridge() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-bridge-prompt.txt"; }
cc-android-science() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-science-prompt.txt"; }
cc-android-sickbay() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-sickbay-prompt.txt"; }
cc-android-engineering() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-engineering-prompt.txt"; }
cc-android-communications() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-communications-prompt.txt"; }
cc-android-navigation() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-navigation-prompt.txt"; }
cc-android-helm() { _cc_launch "$AITEAMFORGE_DIR/android/scripts/prompts/android-helm-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# Freelance Team (ENT)
# ─────────────────────────────────────────────────────────────────────────────
cc-freelance-command() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-command-prompt.txt"; }
cc-freelance-engineering() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-engineering-prompt.txt"; }
cc-freelance-science() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-science-prompt.txt"; }
cc-freelance-sickbay() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-sickbay-prompt.txt"; }
cc-freelance-tactical() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-tactical-prompt.txt"; }
cc-freelance-comms() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-comms-prompt.txt"; }
cc-freelance-helm() { _cc_launch "$AITEAMFORGE_DIR/freelance/scripts/prompts/freelance-helm-prompt.txt"; }

# ─────────────────────────────────────────────────────────────────────────────
# {{ORG_NAME}} Team (VOY) — org plugin provides prompts at {{ORG_SLUG}}/scripts/prompts/
# ─────────────────────────────────────────────────────────────────────────────
cc-{{ORG_SLUG}}-command() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-command-prompt.txt"
}
cc-{{ORG_SLUG}}-engineering() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-engineering-prompt.txt"
}
cc-{{ORG_SLUG}}-science() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-SCIENCE"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-science-prompt.txt"
}
cc-{{ORG_SLUG}}-sickbay() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-SICKBAY"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-sickbay-prompt.txt"
}
cc-{{ORG_SLUG}}-tactical() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-TACTICAL"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-tactical-prompt.txt"
}
cc-{{ORG_SLUG}}-comms() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-COMMS"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-comms-prompt.txt"
}
cc-{{ORG_SLUG}}-helm() {
    export CLAUDE_{{ORG_SLUG}}_THEME="VOY-HELM"
    _cc_launch "$AITEAMFORGE_DIR/{{ORG_SLUG}}/scripts/prompts/{{ORG_SLUG}}-helm-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# DNS Framework Team (LD)
# ─────────────────────────────────────────────────────────────────────────────
cc-dns-command() {
    export CLAUDE_DNS_THEME="LD-COMMAND"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-command-prompt.txt"
}
cc-dns-bugbay() {
    export CLAUDE_DNS_THEME="LD-BUGBAY"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-bugbay-prompt.txt"
}
cc-dns-testing() {
    export CLAUDE_DNS_THEME="LD-TESTING"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-testing-prompt.txt"
}
cc-dns-build() {
    export CLAUDE_DNS_THEME="LD-BUILD"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-build-prompt.txt"
}
cc-dns-refactor() {
    export CLAUDE_DNS_THEME="LD-REFACTOR"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-refactor-prompt.txt"
}
cc-dns-apidesign() {
    export CLAUDE_DNS_THEME="LD-APIDESIGN"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-apidesign-prompt.txt"
}
cc-dns-docs() {
    export CLAUDE_DNS_THEME="LD-DOCS"
    _cc_launch "$AITEAMFORGE_DIR/dns/scripts/prompts/dns-docs-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Academy Team (32nd Century)
# ─────────────────────────────────────────────────────────────────────────────
cc-academy-chancellor() {
    export CLAUDE_ACADEMY_THEME="CHANCELLOR"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-chancellor-prompt.txt"
}
cc-academy-engineering() {
    export CLAUDE_ACADEMY_THEME="ENGINEERING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-engineering-prompt.txt"
}
cc-academy-medical() {
    export CLAUDE_ACADEMY_THEME="MEDICAL"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-medical-prompt.txt"
}
cc-academy-training() {
    export CLAUDE_ACADEMY_THEME="TRAINING"
    _cc_launch "$AITEAMFORGE_DIR/academy/scripts/prompts/academy-training-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Command Team (DSC)
# ─────────────────────────────────────────────────────────────────────────────
cc-command-admiral() {
    export CLAUDE_COMMAND_THEME="ADMIRAL"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-admiral-prompt.txt"
}
cc-command-operations() {
    export CLAUDE_COMMAND_THEME="OPERATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-operations-prompt.txt"
}
cc-command-strategic() {
    export CLAUDE_COMMAND_THEME="STRATEGIC"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-strategic-prompt.txt"
}
cc-command-communications() {
    export CLAUDE_COMMAND_THEME="COMMUNICATIONS"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-communications-prompt.txt"
}
cc-command-intelligence() {
    export CLAUDE_COMMAND_THEME="INTELLIGENCE"
    _cc_launch "$AITEAMFORGE_DIR/command/scripts/prompts/command-intelligence-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# Finance Team (Ferengi Alliance)
# ─────────────────────────────────────────────────────────────────────────────
cc-finance-nagus() {
    export CLAUDE_FINANCE_THEME="NAGUS"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-nagus-prompt.txt"
}
cc-finance-bar() {
    export CLAUDE_FINANCE_THEME="BAR"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-bar-prompt.txt"
}
cc-finance-vault() {
    export CLAUDE_FINANCE_THEME="VAULT"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-vault-prompt.txt"
}
cc-finance-fca() {
    export CLAUDE_FINANCE_THEME="FCA"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-fca-prompt.txt"
}
cc-finance-workshop() {
    export CLAUDE_FINANCE_THEME="WORKSHOP"
    _cc_launch "$AITEAMFORGE_DIR/finance/scripts/prompts/finance-workshop-prompt.txt"
}

# ─────────────────────────────────────────────────────────────────────────────
# GitHub Bot Tools
# ─────────────────────────────────────────────────────────────────────────────
# XACA-1160: the scripts are tap-owned and installed to $AITEAMFORGE_DIR/scripts/
# by install-shell.sh::install_helper_scripts(). Only the SCRIPT location moved —
# each still resolves its App private key at RUNTIME from
# ~/.config/gh-{review,tester}-bot/, which is unchanged and never ships here.
alias gh-bot-review='bash "$AITEAMFORGE_DIR/scripts/gh-bot-review.sh"'
alias gh-bot-test='bash "$AITEAMFORGE_DIR/scripts/gh-bot-test.sh"'

echo "✓ CC aliases loaded (use 'cc-help' for list)"

cc-help() {
    echo ""
    echo "Claude Code CC Aliases"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "iOS (TNG):        cc-ios-bridge, cc-ios-engineering, cc-ios-sickbay"
    echo "                  cc-ios-holodeck, cc-ios-observation, cc-ios-stellar"
    echo ""
    echo "Firebase (DS9):   cc-firebase-ops, cc-firebase-engineering, cc-firebase-holodeck"
    echo "                  cc-firebase-stellar, cc-firebase-sickbay, cc-firebase-observation"
    echo "                  cc-firebase-promenade"
    echo ""
    echo "Android (TOS):    cc-android-bridge, cc-android-science, cc-android-sickbay"
    echo "                  cc-android-engineering, cc-android-communications"
    echo "                  cc-android-navigation, cc-android-helm"
    echo ""
    echo "Freelance (ENT):  cc-freelance-command, cc-freelance-engineering"
    echo "                  cc-freelance-science, cc-freelance-sickbay"
    echo "                  cc-freelance-tactical, cc-freelance-comms, cc-freelance-helm"
    echo ""
    echo "{{ORG_NAME}} (VOY): cc-{{ORG_SLUG}}-command, cc-{{ORG_SLUG}}-engineering"
    echo "                   cc-{{ORG_SLUG}}-science, cc-{{ORG_SLUG}}-sickbay"
    echo "                   cc-{{ORG_SLUG}}-tactical, cc-{{ORG_SLUG}}-comms, cc-{{ORG_SLUG}}-helm"
    echo ""
    echo "DNS (LD):         cc-dns-command, cc-dns-bugbay, cc-dns-testing, cc-dns-build"
    echo "                  cc-dns-refactor, cc-dns-apidesign, cc-dns-docs"
    echo ""
    echo "Academy (32nd):   cc-academy-chancellor, cc-academy-engineering"
    echo "                  cc-academy-medical, cc-academy-training"
    echo ""
    echo "Command (DSC):    cc-command-admiral, cc-command-operations, cc-command-strategic"
    echo "                  cc-command-communications, cc-command-intelligence"
    echo ""
    echo "Finance (Ferengi): cc-finance-nagus, cc-finance-bar, cc-finance-vault"
    echo "                   cc-finance-fca, cc-finance-workshop"
    echo ""
    echo "Core:             cc (context-aware launch), ccc (resume session)"
    echo ""
    echo "Set CC_DEBUG=1 to preview prompt without launching Claude"
    echo ""
}
