#!/bin/bash
# tests/lib/brew-stub.sh — shared, suite-local `brew` stub (XACA-1222-011).
#
# Background: test-xaca-0463-port-allocation.sh and
# test-xaca-1070-mandatory-install.sh (SECTION T) each hand-rolled a nearly
# identical inline `brew` stub — write an executable shell script that logs
# full argv, reports `list` as "already installed" so install-team.sh never
# takes the `brew install` branch, refuses every mutating/unrecognized
# subcommand loudly, plus a hand-rolled `find_brew_violations`/
# `_x1070t_find_brew_violations` grep over that log. Two copies of the same
# ~35-line fixture is exactly the kind of duplication that drifts: XACA-1222
# hardened the SYSTEMIC guard (tests/lib/brew-guard.sh) with a flag-argument
# allowlist and a bare-`tap` carve-out, and neither per-suite stub ever saw
# that update. This file is the single place both suites (and any future
# one) get that behavior from.
#
# This is a SUITE-LOCAL stub, not the systemic tests/lib/brew-guard.sh
# guard. It exists for the small number of suites that drive REAL,
# non-stubbed installer code (install-team.sh) and need `brew list`/`brew
# install` to behave like a specific, controlled fixture (e.g. "always
# already installed") rather than merely being blocked outright. A suite
# that just needs to PREVENT a real brew mutation, with no need to fake
# specific brew output, is already covered by the systemic guard with zero
# per-suite code — see tests/README.md's "Brew Guard" section for when to
# reach for which.
#
# Portability: bash 3.2 (macOS's shipped bash) and bash 5 (CI installs a
# newer bash for some suites) alike — no associative arrays, no `${var,,}`,
# no `mapfile`. The GENERATED stub script itself is `#!/bin/sh` (POSIX),
# matching the two suites' original inline stubs, since it may run under
# whatever `sh` a consumer script under test invokes brew through.

# ─────────────────────────────────────────────────────────────────────────
# brew_stub_install <bin-dir> <log-file>
#
# Writes an executable `brew` into <bin-dir> and truncates <log-file>. The
# CALLER is responsible for prepending <bin-dir> to PATH ahead of the real
# brew (and ahead of tests/lib/brew-guard.sh's shim, if that is also
# active in this process — PATH is a stack, whichever is prepended last/
# closest to the front wins) before invoking the code under test, and for
# exporting AITEAMFORGE_TEST_BREW_STUB_LOG="<log-file>" into that code's
# environment so the stub knows where to log.
#
# Stub behavior (matches tests/lib/brew-guard.sh's own shim semantics,
# XACA-1222-012):
#   list [--cask] <formula>  -> exit 0 ("already installed") — the caller
#                               never falls through to `brew install`.
#   --prefix                  -> a nonexistent path, exit 0.
#   tap  (bare, no args)      -> exit 0, empty stdout (list-only; matches
#                               how production code calls it — see
#                               tests/lib/brew-guard.sh's own bare-tap
#                               carve-out and its rationale).
#   tap <name-or-flag> (any argument at all) -> refuse loudly, exit 1
#                               (a mutation, unlike the bare form above).
#   install|upgrade|untap|reinstall|uninstall|update|services
#                              -> refuse loudly, exit 1.
#   anything else (unrecognized) -> refuse loudly, exit 1 (fail closed).
#
# Every invocation is logged to <log-file> as "brew <arg> <arg> ...\n"
# regardless of outcome, so a caller can assert BOTH "the stub was actually
# reached" (positive evidence — an empty log proves nothing was verified)
# and "no mutating call got through" (via brew_stub_violations).
# ─────────────────────────────────────────────────────────────────────────
brew_stub_install() {
  local _bin_dir="$1"
  local _log_file="$2"

  if [ -z "$_bin_dir" ] || [ -z "$_log_file" ]; then
    echo "brew_stub_install: both <bin-dir> and <log-file> are required" >&2
    return 1
  fi

  mkdir -p "$_bin_dir" || {
    echo "brew_stub_install: mkdir -p '$_bin_dir' failed" >&2
    return 1
  }
  : > "$_log_file" 2>/dev/null || {
    echo "brew_stub_install: could not create/truncate log file '$_log_file'" >&2
    return 1
  }

  cat > "$_bin_dir/brew" <<'BREW_STUB_EOF'
#!/bin/sh
# AUTO-GENERATED by tests/lib/brew-stub.sh brew_stub_install() (XACA-1222-011).
# Do not edit by hand -- regenerate via brew_stub_install. See that
# function's header comment (tests/lib/brew-stub.sh) for the full contract.
#
# Reads its log destination from AITEAMFORGE_TEST_BREW_STUB_LOG at RUN time
# (set by the caller before invoking the code under test), never baked in
# at generation time -- this keeps the generated file identical regardless
# of where a given suite's log happens to live.
_log="${AITEAMFORGE_TEST_BREW_STUB_LOG:-}"
{
    printf '%s' "brew"
    for _a in "$@"; do printf ' %s' "$_a"; done
    printf '\n'
} >> "${_log:-/dev/null}" 2>/dev/null

case "$1" in
    list)
        exit 0
        ;;
    --prefix)
        printf '%s\n' "/nonexistent-xaca-1222-brew-prefix"
        exit 0
        ;;
    tap)
        # Bare `brew tap` (no further args) only LISTS installed taps --
        # matches tests/lib/brew-guard.sh's own bare-tap carve-out. Any
        # argument at all (a tap name, --repair, --force) is a mutation.
        if [ "$#" -eq 1 ]; then
            exit 0
        fi
        echo "brew stub: refusing 'brew tap' with arguments (mutating): $*" >&2
        exit 1
        ;;
    install|upgrade|untap|reinstall|uninstall|update|services)
        echo "brew stub: refusing mutating/network subcommand '$*' (XACA-1222)" >&2
        exit 1
        ;;
    *)
        echo "brew stub: refusing unrecognised subcommand '$*' (XACA-1222)" >&2
        exit 1
        ;;
esac
BREW_STUB_EOF

  chmod +x "$_bin_dir/brew" || {
    echo "brew_stub_install: chmod +x '$_bin_dir/brew' failed" >&2
    return 1
  }
  return 0
}

# ─────────────────────────────────────────────────────────────────────────
# brew_stub_violations <log-file>
#
# Prints every line-anchored MUTATING invocation recorded in <log-file> —
# empty output means none were attempted. Anchored on line-start "brew
# <subcommand>" so a dependency named e.g. "install-helper" appearing as an
# ARGUMENT can never false-match.
#
# `tap` is intentionally split from the flat subcommand list: a bare `brew
# tap` (exactly one field after "brew") is allowed by the stub above and
# must NOT be reported as a violation, but `brew tap <anything>` (a tap
# name, a flag) is a mutation and must be. The alternation's second branch
# requires at least one more field after "tap" to match.
# ─────────────────────────────────────────────────────────────────────────
brew_stub_violations() {
  local _log_file="$1"
  grep -E '^brew (install|upgrade|untap|reinstall|uninstall|update|services)\b|^brew tap [^[:space:]]' "$_log_file" 2>/dev/null || true
}
