#!/bin/bash
#
# Tailscale Funnel Restore Script
# Restores all Funnel routes for LCARS dashboard system
# Auto-generated by aiteamforge installer
#

set -e  # Exit on error

TS="{{TAILSCALE_PATH}}"
FUNNEL_PORT={{FUNNEL_PORT}}

echo "🔧 Restoring Tailscale Funnel configuration..."
echo ""

# Check if Tailscale is running
if ! $TS status &>/dev/null; then
    echo "❌ ERROR: Tailscale is not running or not connected"
    echo "   Launch Tailscale from Applications and try again"
    exit 1
fi

echo "✓ Tailscale is connected"
echo ""

echo "🌐 Setting up Funnel routes (internet-accessible)..."

# Main Fleet Monitor dashboard
$TS funnel --bg --yes http://127.0.0.1:${FUNNEL_PORT}
echo "✓ Port ${FUNNEL_PORT} root configured"

# LCARS team dashboards
{{TEAM_ROUTES}}

echo ""
echo "✅ Funnel restoration complete!"
echo ""
echo "📊 Current configuration:"
$TS funnel status
