class Aiteamforge < Formula
  desc "AITeamForge - AI-powered multi-team development infrastructure"
  homepage "https://github.com/DoubleNode/homebrew-aiteamforge"
  url "https://github.com/DoubleNode/homebrew-aiteamforge.git",
      tag: "v0.11.4"
  license "MIT"
  version "0.11.4"

  # Core dependencies required for aiteamforge to function
  depends_on "python@3"
  depends_on "node"
  depends_on "jq"
  depends_on "gh"
  depends_on "git"
  depends_on "tmux"
  depends_on :macos => :big_sur # iTerm2 and macOS-specific features

  # Optional dependencies for advanced features
  uses_from_macos "rsync" # For sync scripts

  def install
    # Install all core files to libexec (framework location)
    libexec.install Dir["*"]

    # Create bin stubs for main commands
    (bin/"aiteamforge").write <<~EOS
      #!/bin/bash
      # AITeamForge CLI dispatcher
      AITEAMFORGE_HOME="#{libexec}"
      export AITEAMFORGE_HOME
      [ -f "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh" ] && . "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh"
      exec "#{libexec}/bin/aiteamforge-cli.sh" "$@"
    EOS

    (bin/"aiteamforge-setup").write <<~EOS
      #!/bin/bash
      # AITeamForge interactive setup wizard
      AITEAMFORGE_HOME="#{libexec}"
      export AITEAMFORGE_HOME
      [ -f "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh" ] && . "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh"
      exec "#{libexec}/bin/aiteamforge-setup.sh" "$@"
    EOS

    (bin/"aiteamforge-doctor").write <<~EOS
      #!/bin/bash
      # AITeamForge health check and diagnostics
      AITEAMFORGE_HOME="#{libexec}"
      export AITEAMFORGE_HOME
      [ -f "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh" ] && . "#{HOMEBREW_PREFIX}/var/aiteamforge/env.sh"
      exec "#{libexec}/bin/aiteamforge-doctor.sh" "$@"
    EOS

    chmod 0755, bin/"aiteamforge"
    chmod 0755, bin/"aiteamforge-setup"
    chmod 0755, bin/"aiteamforge-doctor"
  end

  def post_install
    var_dir = HOMEBREW_PREFIX/"var/aiteamforge"
    var_dir.mkpath

    # Provision tap-owned Python venv. Unconditionally recreate on every
    # post_install so the venv stays ABI-aligned when Homebrew upgrades python@3.
    python3 = Formula["python@3"].opt_bin/"python3"
    venv    = var_dir/"venv"
    rm_r(venv) if venv.exist?
    system python3, "-m", "venv", venv

    # Freshen pip before installing requirements (cheap insurance, <1s).
    system venv/"bin/python3", "-m", "ensurepip", "--upgrade"
    system venv/"bin/pip", "install", "--upgrade", "pip"

    # Install pinned deps from requirements.txt shipped in the tap.
    # An empty (comments-only) file is a pip no-op — that is fine.
    system venv/"bin/pip", "install", "-r", libexec/"share/requirements.txt"

    # Write env.sh so bin stubs and libexec scripts can locate the venv Python.
    # Generated here (not shipped) because HOMEBREW_PREFIX is resolved at install time.
    env_sh = var_dir/"env.sh"
    env_sh.atomic_write <<~ENVSH
      # AITeamForge Python environment — generated by post_install, do not edit manually
      # Sourced by bin stubs and libexec scripts. Safe to source multiple times.
      # Venv path baked in at install time; independent of caller's HOMEBREW_PREFIX.

      _ATF_VENV="#{HOMEBREW_PREFIX}/var/aiteamforge/venv"

      if [ -d "$_ATF_VENV" ]; then
        export AITEAMFORGE_PYTHON="$_ATF_VENV/bin/python3"
      else
        # Fallback: venv missing (dev mode, non-brew install, or post_install not yet run)
        export AITEAMFORGE_PYTHON="${AITEAMFORGE_PYTHON:-python3}"
        [ "${_ATF_VENV_WARNED:-}" != "1" ] && \
          echo "aiteamforge: WARNING: Python venv not found at $_ATF_VENV" \
               "(run: brew reinstall aiteamforge)" >&2
        export _ATF_VENV_WARNED=1
      fi

      unset _ATF_VENV
    ENVSH
    env_sh.chmod(0644) # world-readable; Homebrew installs are multi-user capable

    # Create installation marker (atomic_write handles overwrite on reinstall)
    marker = var_dir/".installed"
    marker.atomic_write "#{version}\n#{Time.now}"

    ohai "AITeamForge framework installed successfully"
    ohai "Run 'aiteamforge setup' to configure your environment"
  end

  def caveats
    <<~EOS
      AITeamForge has been installed to:
        #{libexec}

      Available commands:
        aiteamforge setup     - Interactive setup wizard
        aiteamforge doctor    - Health check and diagnostics
        aiteamforge status    - Show current environment status
        aiteamforge upgrade   - Upgrade components
        aiteamforge help      - Show help information

      To get started:
        1. Run: aiteamforge setup
        2. Follow the interactive wizard to:
           - Install iTerm2 (if needed)
           - Install Claude Code (if needed)
           - Select teams to configure
           - Set up LCARS Kanban system
           - Configure terminal environment

      The setup wizard will guide you through creating your
      team environment in ~/aiteamforge (or custom location).

      IMPORTANT: The formula installs the FRAMEWORK only.
      Run 'aiteamforge setup' to create your working environment.

      Python dependencies are managed in a tap-owned venv at:
        #{HOMEBREW_PREFIX}/var/aiteamforge/venv
      Pinned deps live in #{libexec}/share/requirements.txt.
      See docs/python-dep-channel-design.md for the full design.

      For troubleshooting: aiteamforge doctor
      For documentation: #{libexec}/docs/
    EOS
  end

  test do
    # Verify main commands exist and are executable
    assert_predicate bin/"aiteamforge", :exist?
    assert_predicate bin/"aiteamforge-setup", :exist?

    # Verify core directories exist (libexec/ subdir mirrors repo structure)
    assert_predicate libexec/"libexec/commands", :exist?
    assert_predicate libexec/"libexec/installers", :exist?
    assert_predicate libexec/"libexec/lib", :exist?
    assert_predicate libexec/"share/templates", :exist?
    assert_predicate libexec/"share/templates/team-connect.sh.template", :exist?
    assert_predicate libexec/"share/teams", :exist?

    # Verify library files exist
    assert_predicate libexec/"libexec/lib/common.sh", :exist?
    assert_predicate libexec/"libexec/lib/config.sh", :exist?
    assert_predicate libexec/"libexec/lib/wizard-ui.sh", :exist?

    # Verify alias templates exist (must ship in released package for install-shell.sh)
    assert_predicate libexec/"share/templates/aliases/agent-aliases.sh", :exist?
    assert_predicate libexec/"share/templates/aliases/cc-aliases.sh", :exist?
    assert_predicate libexec/"share/templates/aliases/worktree-aliases.sh", :exist?

    # Verify Python dependency manifest ships with the tap
    assert_predicate libexec/"share/requirements.txt", :exist?

    # Verify Python env helper ships with the tap
    assert_predicate libexec/"libexec/lib/python-env.sh", :exist?

    # Verify kb-cr namespace + migration script ship in installer payload (XACA-0309)
    assert_predicate libexec/"share/scripts/kb-cr.sh", :exist?
    assert_predicate libexec/"share/scripts/migrate-cr-schema.py", :exist?
    assert_predicate libexec/"share/templates/kanban/cr-schema.json", :exist?

    # Test that setup wizard shows version
    system "#{bin}/aiteamforge-setup", "--help"
  end
end
