#!/bin/bash
# Kanban Helper Functions
# Auto-generated by aiteamforge installer
# Provides kb-* shell functions for kanban board management
#
# Usage: source {{AITEAMFORGE_DIR}}/kanban-helpers.sh

AITEAMFORGE_DIR="{{AITEAMFORGE_DIR}}"

# ─────────────────────────────────────────────────────────────────────────────
# Board Discovery
# ─────────────────────────────────────────────────────────────────────────────

# Find the kanban board file for the current team context
_kb_find_board() {
    local team="${1:-}"

    # If team specified, look for that board
    if [[ -n "$team" ]]; then
        local board_file="$AITEAMFORGE_DIR/kanban/${team}-board.json"
        if [[ -f "$board_file" ]]; then
            echo "$board_file"
            return 0
        fi
    fi

    # Try to detect team from environment
    if [[ -n "${CLAUDE_TEAM:-}" ]]; then
        local board_file="$AITEAMFORGE_DIR/kanban/${CLAUDE_TEAM}-board.json"
        if [[ -f "$board_file" ]]; then
            echo "$board_file"
            return 0
        fi
    fi

    # List available boards
    echo "No board found. Available boards:" >&2
    find "$AITEAMFORGE_DIR/kanban" -name "*-board.json" -type f 2>/dev/null | while read -r f; do
        echo "  $(basename "$f" -board.json)" >&2
    done
    return 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Core Commands
# ─────────────────────────────────────────────────────────────────────────────

# List kanban items
kb-list() {
    local board
    board="$(_kb_find_board "${1:-}")" || return 1
    echo "Kanban Board: $(jq -r '.teamName // .team' "$board")"
    echo "─────────────────────────────────────"
    jq -r '.items | to_entries[] | "\(.key): \(.value.title) [\(.value.status)]"' "$board" 2>/dev/null || {
        echo "(empty board)"
    }
}

# Add a kanban item
kb-add() {
    local title="$1"
    if [[ -z "$title" ]]; then
        echo "Usage: kb-add <title>" >&2
        return 1
    fi

    local board
    board="$(_kb_find_board)" || return 1

    local id
    id=$(jq -r '.metadata.nextId // 1' "$board")
    local team_prefix
    team_prefix=$(jq -r '.team // "ITEM"' "$board" | tr '[:lower:]' '[:upper:]')

    local item_id="${team_prefix}-$(printf '%04d' "$id")"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    jq --arg id "$item_id" \
       --arg title "$title" \
       --arg now "$now" \
       '.items[$id] = {title: $title, status: "backlog", created: $now} | .metadata.nextId = (.metadata.nextId // 1) + 1 | .metadata.lastModified = $now' \
       "$board" > "${board}.tmp" && mv "${board}.tmp" "$board"

    echo "Added: $item_id - $title"
}

# Show board status summary
kb-status() {
    local board
    board="$(_kb_find_board "${1:-}")" || return 1
    echo "Board: $(jq -r '.teamName // .team' "$board")"
    jq -r '.items | to_entries | group_by(.value.status) | .[] | "\(.[0].value.status): \(length) item(s)"' "$board" 2>/dev/null
}

echo "Kanban helpers loaded. Commands: kb-list, kb-add, kb-status"
